#!/usr/bin/env php
<?php

$contents = file_get_contents($argv[1]);

$matched = preg_match_all(
    '/msgid\s+((?:".*(?<!\\\\)"\s*)+)\s+' . 'msgstr\s+((?:".*(?<!\\\\)"\s*)+)/',
    $contents,
    $matches
);

for ($i = 0; $i < $matched; $i++) {
    $msgid = substr(rtrim($matches[1][$i]), 1, -1);
    $msgstr = substr(rtrim($matches[2][$i]), 1, -1);
    echo '"' . prepare($msgid) . '";"' . prepare($msgstr) . "\"\n";
}


function prepare($string, $reverse = false)
{
    if ($reverse) {
        $smap = array('\\', '"', "\n", "\t", "\r");
        $rmap = array('\\\\', '\\"', '\\n"' . "\n" . '"', '\\t', '\\r');
        return (string) str_replace($smap, $rmap, $string);
    } else {
        $smap = array('/"\s+"/', '/\\\\n/', '/\\\\r/', '/\\\\t/', '/\\\\"/', '/\\\\\\\\/');
        $rmap = array('', "\n", "\r", "\t", '"', '\\');
        return (string) preg_replace($smap, $rmap, $string);
    }
}
